services:
  - type: static
    name: event-landing
    buildCommand: cd "landing page/frontend" && npm install && npm run build
    staticPublishPath: "./landing page/frontend/dist"
    routes:
      - type: rewrite
        source: /events/*
        destination: /index.html
      - type: rewrite
        source: /register/*
        destination: /index.html
      - type: rewrite
        source: /about
        destination: /index.html
      - type: rewrite
        source: /contact
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
